/**
 * One-time bootstrap: generates a random AES-256 key and stores it in
 * Supabase Vault as `admin_totp_encryption_key_v1` (migration 0023).
 * Must be run once per environment (local, staging, production each need
 * their own key — never copy a key across environments) before any admin
 * can complete first-login TOTP setup, since encryptTotpSecret() will
 * throw a clear error otherwise.
 *
 * Usage (from apps/admin/):
 *   pnpm generate-totp-vault-key
 *
 * Safe to run more than once accidentally — vault.create_secret with a
 * name that already exists raises a Postgres error rather than silently
 * overwriting an in-use key (which would make every already-enrolled
 * admin's stored TOTP secret undecryptable).
 */
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { config as loadEnv } from 'dotenv';
import { Pool } from 'pg';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
loadEnv({ path: path.resolve(__dirname, '../.env.local') });

async function main() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    console.error('Missing DATABASE_URL in apps/admin/.env.local.');
    process.exit(1);
  }

  const pool = new Pool({ connectionString });
  const key = crypto.randomBytes(32).toString('base64'); // AES-256 = 32 bytes

  try {
    await pool.query(`select vault.create_secret($1, $2, $3)`, [
      key,
      'admin_totp_encryption_key_v1',
      'AES-256-GCM key for platform_admins.totp_secret (Doc 01 §1.3.11). ' +
        'Generated by scripts/generate-totp-vault-key.ts. Do not copy across environments.',
    ]);
    console.log('Vault secret "admin_totp_encryption_key_v1" created.');
    console.log('Admins can now complete TOTP setup on first login.');
  } catch (err) {
    if (err instanceof Error && /duplicate key|already exists/i.test(err.message)) {
      console.error(
        'A secret named "admin_totp_encryption_key_v1" already exists in this environment. ' +
          "Not overwriting it — doing so would make every already-enrolled admin's TOTP secret " +
          'undecryptable. If you really need to rotate the key, that needs a proper migration ' +
          '(re-encrypt existing secrets under a new version), not just replacing this one.',
      );
    } else {
      console.error('Failed to create Vault secret:', err instanceof Error ? err.message : err);
    }
    process.exit(1);
  } finally {
    await pool.end();
  }
}

main();
