/**
 * One-time bootstrap: stores the two secrets migration 0026's pg_cron job
 * needs to invoke send-impersonation-notifications — `cron_edge_function_
 * base_url` and `cron_service_role_key` — in Supabase Vault.
 *
 * These same two secrets are now reused by two later cron jobs that don't
 * register their own: mobile's 0027 (send-digest-notifications) and this
 * session's 0030 (send-announcement-notifications). All three are generic
 * (a base URL + a service-role key), so one registration covers all of
 * them — no new secret names needed as more cron-invoked Edge Functions
 * get added.
 *
 * Must be run once per environment (local, staging, production each point
 * at a different Supabase project, so this is not a value that can be
 * baked into the migration itself). Until this has been run, the
 * scheduled job created in 0026 will fire every 15 minutes and fail with
 * a clear missing-secret error (visible in `cron.job_run_details`) rather
 * than silently doing nothing — same principle as
 * generate-totp-vault-key.ts.
 *
 * Usage (from apps/admin/):
 *   pnpm register-cron-secrets
 *
 * Safe to run more than once — this one intentionally DOES overwrite an
 * existing secret of the same name (unlike the TOTP key), since the
 * service-role key or function URL legitimately can change (key rotation,
 * project migration) and nothing has been encrypted against these values
 * the way TOTP secrets are encrypted against the vault key.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { config as loadEnv } from 'dotenv';
import { Pool } from 'pg';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
loadEnv({ path: path.resolve(__dirname, '../.env.local') });

async function upsertSecret(pool: Pool, name: string, value: string, description: string) {
  const { rows } = await pool.query(`select id from vault.secrets where name = $1`, [name]);
  if (rows.length > 0) {
    await pool.query(`select vault.update_secret($1, $2, $3, $4)`, [
      rows[0].id,
      value,
      name,
      description,
    ]);
    console.log(`Vault secret "${name}" updated.`);
  } else {
    await pool.query(`select vault.create_secret($1, $2, $3)`, [value, name, description]);
    console.log(`Vault secret "${name}" created.`);
  }
}

async function main() {
  const connectionString = process.env.DATABASE_URL;
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!connectionString || !supabaseUrl || !serviceRoleKey) {
    console.error(
      'Missing one of DATABASE_URL, NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY ' +
        'in apps/admin/.env.local.',
    );
    process.exit(1);
  }

  const functionsBaseUrl = `${supabaseUrl.replace(/\/$/, '')}/functions/v1`;
  const pool = new Pool({ connectionString });

  try {
    await upsertSecret(
      pool,
      'cron_edge_function_base_url',
      functionsBaseUrl,
      'Base URL for Edge Function invocations from pg_cron (migration 0026). ' +
        'Generated by scripts/register-cron-secrets.ts.',
    );
    await upsertSecret(
      pool,
      'cron_service_role_key',
      serviceRoleKey,
      'Service-role key used as the Authorization bearer token when pg_cron ' +
        'invokes send-impersonation-notifications (migration 0026). ' +
        'Generated by scripts/register-cron-secrets.ts. Do not copy across environments.',
    );
    console.log('send-impersonation-notifications is now scheduled and authorized to run.');
  } catch (err) {
    console.error('Failed to register cron secrets:', err instanceof Error ? err.message : err);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

main();
