import {
  dashboardStats,
  quickActions,
  recentActivities,
  weeklyCalendar,
  weeklyCashflow,
  weeklyCashflowLabels,
} from '@/components/contractor/mock-data';
import {
  CalendarGrid,
  MetricCard,
  MiniBarChart,
  PageHeader,
  ProgressBar,
  SectionCard,
  TimelineList,
} from '@/components/contractor/Screen';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';

export default function DashboardPage() {
  return (
    <div className="mx-auto flex w-full max-w-[1600px] flex-col gap-6 px-4 py-4 sm:px-6 lg:px-8 lg:py-8">
      <PageHeader
        eyebrow="Command center"
        title="Tunisia Construction OS"
        description="Manage projects, dispatch, workforce, vehicles, materials, billing, and client reporting from one modern operations dashboard."
        actions={
          <>
            <Button variant="secondary">View reports</Button>
            <Button>Quick action</Button>
          </>
        }
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {dashboardStats.map((stat) => (
          <MetricCard
            key={stat.label}
            label={stat.label}
            value={stat.value}
            delta={stat.delta}
            tone={stat.tone}
            footnote={stat.footnote}
          />
        ))}
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]">
        <SectionCard
          title="Budget consumption"
          description="Weekly cash flow and budget pressure across active jobs."
          actions={<Button variant="text">Open analytics</Button>}
        >
          <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
            <div className="bg-neutral-25 rounded-[20px] border border-neutral-100 p-5">
              <div className="mb-5 flex items-center justify-between">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-[0.1em] text-neutral-500">
                    Weekly revenue trend
                  </p>
                  <p className="mt-1 text-sm text-neutral-500">
                    TND generated by completed milestones.
                  </p>
                </div>
                <div className="text-right">
                  <div className="font-display text-2xl font-semibold text-neutral-900">246.8k</div>
                  <div className="text-success text-xs">+14% vs last month</div>
                </div>
              </div>
              <MiniBarChart values={weeklyCashflow} labels={weeklyCashflowLabels} />
            </div>

            <Card className="p-5">
              <div className="space-y-4">
                <div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-medium text-neutral-900">Budget consumed</span>
                    <span className="text-neutral-500">68%</span>
                  </div>
                  <div className="mt-2">
                    <ProgressBar value={68} tone="warning" />
                  </div>
                </div>
                <div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-medium text-neutral-900">Payroll allocated</span>
                    <span className="text-neutral-500">54%</span>
                  </div>
                  <div className="mt-2">
                    <ProgressBar value={54} tone="success" />
                  </div>
                </div>
                <div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-medium text-neutral-900">Materials committed</span>
                    <span className="text-neutral-500">81%</span>
                  </div>
                  <div className="mt-2">
                    <ProgressBar value={81} tone="danger" />
                  </div>
                </div>
              </div>
            </Card>
          </div>
        </SectionCard>

        <SectionCard title="Quick actions" description="Frequently used operational shortcuts.">
          <div className="grid grid-cols-2 gap-3">
            {quickActions.map((action) => (
              <button
                key={action}
                className="bg-neutral-25 hover:border-accent-200 hover:bg-accent-50 hover:text-accent-700 rounded-2xl border border-neutral-100 px-4 py-4 text-left text-sm font-medium text-neutral-900 transition-colors"
              >
                {action}
              </button>
            ))}
          </div>
        </SectionCard>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <SectionCard
          title="Recent activities"
          description="The latest operational events across the platform."
        >
          <TimelineList items={recentActivities} />
        </SectionCard>

        <div className="grid gap-6">
          <SectionCard title="Calendar" description="Planning window for the current week.">
            <CalendarGrid days={weeklyCalendar} />
          </SectionCard>

          <SectionCard
            title="Today's priorities"
            description="High-signal reminders for the site team."
          >
            <div className="space-y-3">
              {[
                'Confirm vehicle allocation before 08:30',
                'Upload progress photos for Sites 2 and 4',
                'Approve fuel expenses submitted yesterday',
                'Send invoice reminders to two overdue clients',
              ].map((item) => (
                <div
                  key={item}
                  className="bg-neutral-25 flex items-start gap-3 rounded-2xl px-4 py-3"
                >
                  <span className="bg-accent-600 mt-1 h-2.5 w-2.5 rounded-full" />
                  <p className="text-sm leading-6 text-neutral-900">{item}</p>
                </div>
              ))}
            </div>
          </SectionCard>
        </div>
      </div>
    </div>
  );
}
