import { Model } from '@nozbe/watermelondb';
import { date, field, readonly, text } from '@nozbe/watermelondb/decorators';

/**
 * apps/mobile/src/db/models/Advance.ts
 *
 * Doc 01 §1.11 money-moving action — local mirror of the server `advances`
 * table (0007, `updated_at` added 0045). `idempotencyKey` is set once at
 * local creation and never regenerated by the sync adapter on retry — the
 * whole point of carrying it through unchanged is that a push retried
 * after a dropped connection lands on the same server-side idempotency
 * check every time, not a new one.
 *
 * PHASE 18 REDO — append-only per Doc 01 §1.9: creation
 * (create_advance/request_advance) and approval (approve_advance) are both
 * idempotency-keyed RPCs, never a raw client-side UPDATE, so there is no
 * offline field-merge scenario on this table. (This model briefly carried
 * a `field_versions` column earlier this same conversation, built for
 * exactly the "worker's offline amount edit vs. contractor's offline
 * approval on the same row" scenario the field-level-merge design
 * described — that scenario doesn't actually arise here: approval always
 * goes through approve_advance, which never runs offline in this app's
 * real design, so there's no concurrent-UPDATE case to protect against.
 * See schema.ts's header for the full correction.)
 */
export default class Advance extends Model {
  static table = 'advances';

  @text('org_id') orgId!: string;
  @text('worker_id') workerId!: string;
  @field('amount') amount!: number;
  @text('reason') reason!: string | null;
  @text('status') status!: string;
  @text('requested_by') requestedBy!: string | null;
  @text('approved_by') approvedBy!: string | null;
  @text('idempotency_key') idempotencyKey!: string | null;
  @readonly @date('created_at') createdAt!: Date;
  @readonly @date('updated_at') updatedAt!: Date;
}
